### ISSUE TITLE
Chaskey rotation numbers for halfsiphash

### ISSUE THREAD

**Issue by funny-falcon** [veorq/SipHash#5]
http://mouha.be/chaskey/

**Comment by veorq** [comment]
Thanks again, should have thought of those! Added in 7ce7f0470961555956a12cdf81474e68d1e89610

**Comment by pishposh** [comment]
@veorq Hi! I noticed the second pair of rotation constants in [HalfSipHash](https://github.com/veorq/SipHash/blob/8bdd0a43851832edd612e9019834451cbeb00b1a/halfsiphash.c#L53-L56) (v<sub>3</sub> <<<= 7, v<sub>1</sub> <<<= 13) is swapped as compared to [Chaskey’s constants](http://mouha.be/wp-content/uploads/chaskey-speed.c) (v<sub>3</sub> <<<= 13, v<sub>1</sub> <<<= 7). I’m not sure how much it matters, but is this intentional?

**Comment by veorq** [comment]
Yeah that's a known difference, not a problem, thanks for reporting though :)

**Comment by pishposh** [comment]
Thanks, just checking! Does it improve avalanche or something? I’d be curious to know why.
